"use client";

import { useMemo, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";

type ReviewValues = {
  documentType: "invoice" | "credit_note" | null;
  supplierName: string | null;
  customerName: string | null;
  invoiceNumber: string | null;
  invoiceDate: string | null;
  dueDate: string | null;
  subtotal: number | null;
  vatAmount: number | null;
  total: number | null;
  currency: string | null;
  description: string | null;
  invoiceType: "purchase" | "sale" | null;
  categoryId: string | null;
};

type CategoryOption = { id: string; simple_label: string; description_simple: string | null };
type Draft = {
  documentType: "invoice" | "credit_note" | ""; supplierName: string; customerName: string; invoiceNumber: string;
  invoiceDate: string; dueDate: string; subtotal: string; vatAmount: string; total: string; currency: string;
  description: string; invoiceType: "purchase" | "sale" | ""; categoryId: string;
};
type ArithmeticStatus = "incomplete" | "ok" | "mismatch" | "invalid";
type CorrectionFieldProps = { id: string; label: string; help: string; children: ReactNode; note?: string; wide?: boolean };

function CorrectionField({ id, label, help, children, note, wide = false }: CorrectionFieldProps) {
  return <div className={`invoice-correction-field${wide ? " invoice-correction-wide" : ""}`}><div className="invoice-correction-label-row"><label htmlFor={id}>{label}</label><details className="invoice-field-help"><summary aria-label={`Uitleg over ${label}`}>ⓘ</summary><div>{help}</div></details></div>{children}{note ? <small>{note}</small> : null}</div>;
}
function toDraft(values: ReviewValues): Draft { return { documentType: values.documentType ?? "", supplierName: values.supplierName ?? "", customerName: values.customerName ?? "", invoiceNumber: values.invoiceNumber ?? "", invoiceDate: values.invoiceDate ?? "", dueDate: values.dueDate ?? "", subtotal: values.subtotal === null ? "" : String(values.subtotal), vatAmount: values.vatAmount === null ? "" : String(values.vatAmount), total: values.total === null ? "" : String(values.total), currency: values.currency ?? "", description: values.description ?? "", invoiceType: values.invoiceType ?? "", categoryId: values.categoryId ?? "" }; }
function parseOptionalNumber(value: string) { if (!value.trim()) return null; const parsed = Number(value.replace(",", ".")); return Number.isFinite(parsed) ? parsed : Number.NaN; }
function numberOrNull(value: string) { const parsed = parseOptionalNumber(value); if (parsed === null) return null; if (Number.isNaN(parsed)) throw new Error("Controleer de bedragen. Gebruik bijvoorbeeld 121,00."); return parsed; }
function arithmeticStatus(draft: Draft): ArithmeticStatus { const subtotal = parseOptionalNumber(draft.subtotal); const vat = parseOptionalNumber(draft.vatAmount); const total = parseOptionalNumber(draft.total); if ([subtotal, vat, total].some((value) => typeof value === "number" && Number.isNaN(value))) return "invalid"; if (subtotal === null || vat === null || total === null) return "incomplete"; return Math.abs((subtotal + vat) - total) <= 0.02 ? "ok" : "mismatch"; }
function confirmationIssues(values: ReviewValues) {
  const issues: string[] = [];
  if (values.documentType !== "invoice" && values.documentType !== "credit_note") issues.push("documenttype");
  if (values.invoiceType !== "purchase" && values.invoiceType !== "sale") issues.push("aankoop of verkoop");
  if (!values.invoiceDate) issues.push("factuurdatum");
  if (!values.currency || !/^[A-Z]{3}$/.test(values.currency)) issues.push("valuta");
  if (values.subtotal === null) issues.push("bedrag zonder btw");
  if (values.vatAmount === null) issues.push("btw-bedrag");
  if (values.total === null) issues.push("totaalbedrag");
  if (arithmeticStatus(toDraft(values)) === "mismatch") issues.push("bedragen die niet optellen");
  return issues;
}

export default function InvoiceReviewActions({ invoiceId, values, categories }: { invoiceId: string; values: ReviewValues; categories: CategoryOption[] }) {
  const router = useRouter(); const initialDraft = useMemo(() => toDraft(values), [values]); const [draft, setDraft] = useState<Draft>(initialDraft); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState<"confirm" | "save" | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const amountStatus = useMemo(() => arithmeticStatus(draft), [draft]); const issues = useMemo(() => confirmationIssues(values), [values]); const canConfirm = issues.length === 0;
  async function confirm() { if (busy || editing || !canConfirm) return; setBusy("confirm"); setError(null); setNotice(null); try { const response = await fetch(`/api/invoices/${invoiceId}/confirm`, { method: "POST" }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Bevestiging mislukt."); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Bevestiging mislukt."); } finally { setBusy(null); } }
  function update<K extends keyof Draft>(field: K, value: Draft[K]) { setDraft((current) => ({ ...current, [field]: value })); }
  function toggleEditing() { setError(null); setNotice(null); if (editing) { setDraft(toDraft(values)); setEditing(false); return; } setDraft(toDraft(values)); setEditing(true); }
  async function saveCorrections() { if (busy) return; setError(null); setNotice(null); try { if (amountStatus === "invalid") throw new Error("Controleer de bedragen. Gebruik bijvoorbeeld 121,00."); if (amountStatus === "mismatch") throw new Error("Bedrag zonder btw + btw komt niet overeen met het totaal. Controleer deze drie bedragen eerst."); const nextValues: ReviewValues = { documentType: draft.documentType || null, supplierName: draft.supplierName.trim() || null, customerName: draft.customerName.trim() || null, invoiceNumber: draft.invoiceNumber.trim() || null, invoiceDate: draft.invoiceDate || null, dueDate: draft.dueDate || null, subtotal: numberOrNull(draft.subtotal), vatAmount: numberOrNull(draft.vatAmount), total: numberOrNull(draft.total), currency: draft.currency.trim() ? draft.currency.trim().toUpperCase() : null, description: draft.description.trim() || null, invoiceType: draft.invoiceType || null, categoryId: draft.categoryId || null }; const corrections: Record<string, string | number | null> = {}; for (const key of Object.keys(nextValues) as Array<keyof ReviewValues>) if (nextValues[key] !== values[key]) corrections[key] = nextValues[key]; if (!Object.keys(corrections).length) throw new Error("Je hebt nog niets aangepast."); setBusy("save"); const response = await fetch(`/api/invoices/${invoiceId}/correct`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(corrections) }); const body = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(body.error ?? "De aanpassingen konden niet worden opgeslagen."); setDraft(toDraft(nextValues)); setNotice(body.message ?? "Je aanpassingen zijn veilig opgeslagen."); setEditing(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "De aanpassingen konden niet worden opgeslagen."); } finally { setBusy(null); } }
  return <div className="invoice-review-block"><div className="invoice-review-actions"><button className="button" type="button" disabled={Boolean(busy) || editing || !canConfirm} onClick={confirm}>{busy === "confirm" ? "Bevestigen..." : "Ja, dit klopt"}</button>{!editing ? <button className="button button-secondary" type="button" disabled={Boolean(busy)} onClick={toggleEditing}>Aanpassen</button> : null}<span className="muted">{editing ? "Sla je wijzigingen eerst op. Pas daarna kun je de factuur bevestigen." : canConfirm ? "Bevestig alleen als de gegevens kloppen. Aanpassingen worden apart bijgehouden; de oorspronkelijke AI-uitlezing blijft bestaan." : "Deze factuur heeft nog controle nodig. Kies ‘Aanpassen’ om ontbrekende of onzekere gegevens veilig te vervolledigen."}</span></div>{!editing && !canConfirm ? <div className="invoice-read-warning" role="status" aria-live="polite"><strong>Deze factuur is nog niet klaar om te bevestigen.</strong><span>Controleer eerst {issues.join(" en ")}. Zo voorkomen we dat onbetrouwbare gegevens in je dashboard terechtkomen. Vul alleen in wat je op de factuur kunt controleren.</span></div> : null}{editing ? <div className="invoice-correction-panel"><div className="invoice-correction-intro"><strong>Pas alleen aan wat fout of onduidelijk is</strong><span>Leeg laten betekent dat het gegeven niet betrouwbaar bekend is. Je correctie wordt als apart auditspoor bewaard en overschrijft de oorspronkelijke AI-uitlezing niet.</span></div><div className="invoice-correction-grid">
<CorrectionField id="correction-document-type" label="Documenttype" help="Een factuur vraagt betaling voor een aankoop of verkoop. Een creditnota corrigeert een eerdere factuur. Zie je het niet duidelijk op het document? Kies ‘Niet zeker’. "><select id="correction-document-type" value={draft.documentType} onChange={(e) => update("documentType", e.target.value as Draft["documentType"])}><option value="">Niet zeker</option><option value="invoice">Factuur</option><option value="credit_note">Creditnota</option></select></CorrectionField>
<CorrectionField id="correction-invoice-type" label="Aankoop of verkoop" help="Aankoop betekent dat jouw bedrijf de factuur ontvangt. Verkoop betekent dat jouw bedrijf ze aan een klant stuurt."><select id="correction-invoice-type" value={draft.invoiceType} onChange={(e) => update("invoiceType", e.target.value as Draft["invoiceType"])}><option value="">Niet zeker</option><option value="purchase">Aankoop</option><option value="sale">Verkoop</option></select></CorrectionField>
<CorrectionField id="correction-category" label="Categorie" help="Een eenvoudige groep voor je overzicht. Twijfel je? Kies ‘Niet zeker’." note="Een correctie kan als bedrijfsvoorkeur worden onthouden."><select id="correction-category" value={draft.categoryId} onChange={(e) => update("categoryId", e.target.value)}><option value="">Niet zeker</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.simple_label}</option>)}</select></CorrectionField>
<CorrectionField id="correction-supplier" label="Leverancier" help="Het bedrijf dat levert. Niet duidelijk? Laat leeg."><input id="correction-supplier" value={draft.supplierName} maxLength={500} onChange={(e) => update("supplierName", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-customer" label="Klant" help="Voor wie de factuur bedoeld is. Niet duidelijk? Laat leeg."><input id="correction-customer" value={draft.customerName} maxLength={500} onChange={(e) => update("customerName", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-invoice-number" label="Factuurnummer" help="De unieke referentie op de factuur. Verzin geen nummer."><input id="correction-invoice-number" value={draft.invoiceNumber} maxLength={200} onChange={(e) => update("invoiceNumber", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-currency" label="Valuta" help="De munt waarin de bedragen staan, bijvoorbeeld EUR. Niet zeker? Laat leeg."><input id="correction-currency" value={draft.currency} maxLength={3} placeholder="EUR" onChange={(e) => update("currency", e.target.value.toUpperCase())} /></CorrectionField>
<CorrectionField id="correction-invoice-date" label="Factuurdatum" help="De datum waarop de factuur is opgesteld. Niet duidelijk? Laat leeg."><input id="correction-invoice-date" type="date" value={draft.invoiceDate} onChange={(e) => update("invoiceDate", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-due-date" label="Vervaldatum" help="De datum tegen wanneer betaald moet zijn. Niet duidelijk? Laat leeg."><input id="correction-due-date" type="date" value={draft.dueDate} onChange={(e) => update("dueDate", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-subtotal" label="Bedrag zonder btw" help="Het bedrag vóór btw. Neem alleen over wat je op het document ziet."><input id="correction-subtotal" inputMode="decimal" value={draft.subtotal} placeholder="100,00" onChange={(e) => update("subtotal", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-vat" label="Btw" help="Het apart vermelde btw-bedrag. Bij 0 btw mag je 0 invullen."><input id="correction-vat" inputMode="decimal" value={draft.vatAmount} placeholder="21,00" onChange={(e) => update("vatAmount", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-total" label="Totaal" help="Het totale factuurbedrag. Neem dit rechtstreeks over."><input id="correction-total" inputMode="decimal" value={draft.total} placeholder="121,00" onChange={(e) => update("total", e.target.value)} /></CorrectionField>
<CorrectionField id="correction-description" label="Omschrijving" help="Een korte omschrijving van wat gekocht of verkocht is." wide><textarea id="correction-description" value={draft.description} maxLength={2000} rows={3} onChange={(e) => update("description", e.target.value)} /></CorrectionField>
</div>{amountStatus === "invalid" ? <div className="invoice-read-warning" role="alert"><strong>Controleer de bedragen.</strong><span>Gebruik alleen cijfers, bijvoorbeeld 121,00.</span></div> : null}{amountStatus === "mismatch" ? <div className="invoice-read-warning" role="alert"><strong>De bedragen tellen niet helemaal op.</strong><span>Bedrag zonder btw + btw moet overeenkomen met het totaal.</span></div> : null}<div className="invoice-correction-actions"><button className="button" type="button" disabled={Boolean(busy) || amountStatus === "invalid" || amountStatus === "mismatch"} onClick={saveCorrections}>{busy === "save" ? "Opslaan..." : "Aanpassingen opslaan"}</button><button className="button button-secondary" type="button" disabled={Boolean(busy)} onClick={toggleEditing}>Annuleren</button></div></div> : null}{error ? <div className="invoice-action-message is-error" role="alert">{error}</div> : null}{notice ? <div className="invoice-action-message is-success" role="status">{notice}</div> : null}</div>;
}