#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="ai-bedrijfsadministratie"
DB_CONTAINER="supabase_db_${PROJECT_ID}"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"; supabase stop --no-backup >/dev/null 2>&1 || true' EXIT

USER_ID="11111111-1111-4111-8111-111111111111"
COMPANY_ID="22222222-2222-4222-8222-222222222222"
DOCUMENT_ID="33333333-3333-4333-8333-333333333333"
INVOICE_ID="44444444-4444-4444-8444-444444444444"
DEADLINE_ID="55555555-5555-4555-8555-555555555555"
ALERT_ID="66666666-6666-4666-8666-666666666666"
STORAGE_PATH="company/${COMPANY_ID}/documents/${DOCUMENT_ID}/original.pdf"

run_psql() {
  docker exec -i "$DB_CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d postgres "$@"
}

scalar() {
  run_psql -Atc "$1" | tr -d '\r\n'
}

echo "Starting local Supabase stack..."
supabase start
supabase db reset --local --no-seed

echo "Seeding one synthetic tenant with linked operational data..."
run_psql <<SQL
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values (
  '00000000-0000-0000-0000-000000000000',
  '${USER_ID}', 'authenticated', 'authenticated', 'restore-drill@example.invalid',
  crypt('restore-drill-only', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(),
  '', '', '', ''
);

insert into public.companies (id, name, enterprise_number, profile_status)
values ('${COMPANY_ID}', 'Restore Drill BV', '0123456789', 'complete');

insert into public.company_members (company_id, user_id, role, status)
values ('${COMPANY_ID}', '${USER_ID}', 'owner', 'active');

insert into public.documents (
  id, company_id, uploaded_by, original_filename, display_name, mime_type,
  storage_path, file_hash, document_type, processing_status, review_status
) values (
  '${DOCUMENT_ID}', '${COMPANY_ID}', '${USER_ID}', 'restore-drill.pdf',
  'Restore drill factuur', 'application/pdf', '${STORAGE_PATH}',
  'restore-drill-hash', 'invoice', 'processed', 'confirmed'
);

insert into public.invoices (
  id, company_id, document_id, invoice_type, supplier_name, customer_name,
  invoice_number, invoice_date, due_date, currency, subtotal, vat_amount, total,
  extraction_confidence, review_status, approved_at, approved_by
) values (
  '${INVOICE_ID}', '${COMPANY_ID}', '${DOCUMENT_ID}', 'purchase',
  'Test Leverancier BV', 'Restore Drill BV', 'RESTORE-001',
  '2026-09-01', '2026-09-30', 'EUR', 100.00, 21.00, 121.00,
  0.9900, 'confirmed', now(), '${USER_ID}'
);

insert into public.deadlines (
  id, company_id, type, simple_title, due_date, status, applicability_status
) values (
  '${DEADLINE_ID}', '${COMPANY_ID}', 'restore_test', 'Hersteltest deadline',
  '2026-10-01', 'open', 'verified'
);

insert into public.alerts (id, company_id, severity, type, title, message, status)
values (
  '${ALERT_ID}', '${COMPANY_ID}', 'info', 'restore_test',
  'Hersteltest', 'Synthetische waarschuwing voor backup/restore.', 'open'
);
SQL

cat > "$WORKDIR/original.pdf" <<'PDF'
%PDF-1.4
% Synthetic restore-drill document. No customer data.
1 0 obj << /Type /Catalog >> endobj
trailer << /Root 1 0 R >>
%%EOF
PDF
ORIGINAL_SHA="$(sha256sum "$WORKDIR/original.pdf" | awk '{print $1}')"

# Load local service-role credentials generated by the CLI.
eval "$(supabase status -o env | grep -E '^(API_URL|SERVICE_ROLE_KEY)=')"
: "${API_URL:?local API URL missing}"
: "${SERVICE_ROLE_KEY:?local service-role key missing}"

curl --fail --silent --show-error \
  -X POST "${API_URL}/storage/v1/object/company-documents/${STORAGE_PATH}" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
  -H "Content-Type: application/pdf" \
  --data-binary @"$WORKDIR/original.pdf" >/dev/null

EXPECTED_COMPANY="$(scalar "select name from public.companies where id='${COMPANY_ID}'")"
EXPECTED_INVOICE="$(scalar "select concat(invoice_number,'|',subtotal,'|',vat_amount,'|',total,'|',review_status) from public.invoices where id='${INVOICE_ID}'")"
EXPECTED_DOCUMENT="$(scalar "select concat(original_filename,'|',storage_path,'|',review_status) from public.documents where id='${DOCUMENT_ID}'")"
EXPECTED_DEADLINE="$(scalar "select concat(simple_title,'|',due_date,'|',status) from public.deadlines where id='${DEADLINE_ID}'")"

echo "Taking logical backup of app-owned tenant data..."
docker exec "$DB_CONTAINER" pg_dump -U postgres -d postgres -Fc --data-only \
  --table=public.profiles \
  --table=public.companies \
  --table=public.company_members \
  --table=public.documents \
  --table=public.invoices \
  --table=public.invoice_extractions \
  --table=public.category_preferences \
  --table=public.deadlines \
  --table=public.alerts \
  --table=public.audit_logs \
  --table=public.ai_interactions \
  -f /tmp/ai-bedrijfsadministratie.dump
docker cp "${DB_CONTAINER}:/tmp/ai-bedrijfsadministratie.dump" "$WORKDIR/backup.dump" >/dev/null

curl --fail --silent --show-error \
  "${API_URL}/storage/v1/object/authenticated/company-documents/${STORAGE_PATH}" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
  -o "$WORKDIR/storage-backup.pdf"
BACKUP_SHA="$(sha256sum "$WORKDIR/storage-backup.pdf" | awk '{print $1}')"
test "$BACKUP_SHA" = "$ORIGINAL_SHA"

echo "Simulating loss of tenant data and original document..."
run_psql <<SQL
truncate table
  public.invoice_extractions,
  public.category_preferences,
  public.audit_logs,
  public.alerts,
  public.deadlines,
  public.invoices,
  public.documents,
  public.company_members,
  public.profiles,
  public.companies
restart identity cascade;
SQL

curl --fail --silent --show-error \
  -X DELETE "${API_URL}/storage/v1/object/company-documents/${STORAGE_PATH}" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" >/dev/null

test "$(scalar "select count(*) from public.companies where id='${COMPANY_ID}'")" = "0"
test "$(scalar "select count(*) from public.invoices where id='${INVOICE_ID}'")" = "0"

if curl --fail --silent \
  "${API_URL}/storage/v1/object/authenticated/company-documents/${STORAGE_PATH}" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
  -o /dev/null; then
  echo "Expected original document to be absent after simulated loss." >&2
  exit 1
fi

echo "Restoring database backup..."
docker cp "$WORKDIR/backup.dump" "${DB_CONTAINER}:/tmp/restore.dump" >/dev/null
docker exec "$DB_CONTAINER" pg_restore -U postgres -d postgres --data-only --disable-triggers --exit-on-error /tmp/restore.dump

echo "Restoring original document to the exact storage path..."
curl --fail --silent --show-error \
  -X POST "${API_URL}/storage/v1/object/company-documents/${STORAGE_PATH}" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
  -H "Content-Type: application/pdf" \
  --data-binary @"$WORKDIR/storage-backup.pdf" >/dev/null

RESTORED_COMPANY="$(scalar "select name from public.companies where id='${COMPANY_ID}'")"
RESTORED_INVOICE="$(scalar "select concat(invoice_number,'|',subtotal,'|',vat_amount,'|',total,'|',review_status) from public.invoices where id='${INVOICE_ID}'")"
RESTORED_DOCUMENT="$(scalar "select concat(original_filename,'|',storage_path,'|',review_status) from public.documents where id='${DOCUMENT_ID}'")"
RESTORED_DEADLINE="$(scalar "select concat(simple_title,'|',due_date,'|',status) from public.deadlines where id='${DEADLINE_ID}'")"

test "$RESTORED_COMPANY" = "$EXPECTED_COMPANY"
test "$RESTORED_INVOICE" = "$EXPECTED_INVOICE"
test "$RESTORED_DOCUMENT" = "$EXPECTED_DOCUMENT"
test "$RESTORED_DEADLINE" = "$EXPECTED_DEADLINE"
test "$(scalar "select count(*) from public.company_members where company_id='${COMPANY_ID}' and user_id='${USER_ID}'")" = "1"
test "$(scalar "select count(*) from public.alerts where id='${ALERT_ID}'")" = "1"

curl --fail --silent --show-error \
  "${API_URL}/storage/v1/object/authenticated/company-documents/${STORAGE_PATH}" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
  -o "$WORKDIR/restored.pdf"
RESTORED_SHA="$(sha256sum "$WORKDIR/restored.pdf" | awk '{print $1}')"
test "$RESTORED_SHA" = "$ORIGINAL_SHA"

echo "RESTORE_DRILL_PASS company=1 invoice=1 document=1 deadline=1 storage_sha256=${RESTORED_SHA}"
