#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="ai-bedrijfsadministratie"
DB_CONTAINER="supabase_db_${PROJECT_ID}"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"; supabase stop --no-backup >/dev/null 2>&1 || true' EXIT

PASSWORD="TenantTest-2026!"
USER_A="11111111-1111-4111-8111-111111111111"
USER_B="22222222-2222-4222-8222-222222222222"
COMPANY_A="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
COMPANY_B="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"
DOCUMENT_A="aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa"
DOCUMENT_B="bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb"
INVOICE_A="aaaaaaaa-3333-4333-8333-aaaaaaaaaaaa"
INVOICE_B="bbbbbbbb-4444-4444-8444-bbbbbbbbbbbb"
DEADLINE_A="aaaaaaaa-5555-4555-8555-aaaaaaaaaaaa"
DEADLINE_B="bbbbbbbb-6666-4666-8666-bbbbbbbbbbbb"
ALERT_A="aaaaaaaa-7777-4777-8777-aaaaaaaaaaaa"
ALERT_B="bbbbbbbb-8888-4888-8888-bbbbbbbbbbbb"
PATH_A="company/${COMPANY_A}/documents/${DOCUMENT_A}/original.pdf"
PATH_B="company/${COMPANY_B}/documents/${DOCUMENT_B}/original.pdf"

run_psql() {
  docker exec -i "$DB_CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d postgres "$@"
}

json_len() {
  jq 'length'
}

assert_http_not_2xx() {
  local code="$1"
  local label="$2"
  if [[ "$code" =~ ^2 ]]; then
    echo "SECURITY FAILURE: ${label} unexpectedly returned HTTP ${code}." >&2
    exit 1
  fi
}

echo "Starting isolated local Supabase stack..."
supabase start
supabase db reset --local --no-seed

echo "Creating two synthetic users and two fully separate companies..."
run_psql <<SQL
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values
(
  '00000000-0000-0000-0000-000000000000', '${USER_A}', 'authenticated', 'authenticated',
  'tenant-a@example.com', crypt('${PASSWORD}', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', ''
),
(
  '00000000-0000-0000-0000-000000000000', '${USER_B}', 'authenticated', 'authenticated',
  'tenant-b@example.com', crypt('${PASSWORD}', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', ''
);

insert into public.companies (id, name, enterprise_number, profile_status) values
('${COMPANY_A}', 'Tenant A BV', '0123456789', 'complete'),
('${COMPANY_B}', 'Tenant B BV', '9876543210', 'complete');

insert into public.company_members (company_id, user_id, role, status) values
('${COMPANY_A}', '${USER_A}', 'owner', 'active'),
('${COMPANY_B}', '${USER_B}', 'owner', 'active');

insert into public.documents (
  id, company_id, uploaded_by, original_filename, display_name, mime_type,
  storage_path, file_hash, document_type, processing_status, review_status
) values
('${DOCUMENT_A}', '${COMPANY_A}', '${USER_A}', 'tenant-a.pdf', 'Factuur A', 'application/pdf', '${PATH_A}', 'hash-a', 'invoice', 'processed', 'confirmed'),
('${DOCUMENT_B}', '${COMPANY_B}', '${USER_B}', 'tenant-b.pdf', 'Factuur B', 'application/pdf', '${PATH_B}', 'hash-b', 'invoice', 'processed', 'confirmed');

insert into public.invoices (
  id, company_id, document_id, invoice_type, supplier_name, invoice_number,
  invoice_date, currency, subtotal, vat_amount, total, extraction_confidence, review_status
) values
('${INVOICE_A}', '${COMPANY_A}', '${DOCUMENT_A}', 'purchase', 'Leverancier A', 'A-001', '2026-09-01', 'EUR', 100, 21, 121, 0.99, 'confirmed'),
('${INVOICE_B}', '${COMPANY_B}', '${DOCUMENT_B}', 'purchase', 'Leverancier B', 'B-001', '2026-09-01', 'EUR', 200, 42, 242, 0.99, 'confirmed');

insert into public.deadlines (id, company_id, type, simple_title, due_date, status, applicability_status) values
('${DEADLINE_A}', '${COMPANY_A}', 'tenant_test', 'Deadline A', '2026-10-01', 'open', 'verified'),
('${DEADLINE_B}', '${COMPANY_B}', 'tenant_test', 'Deadline B', '2026-10-01', 'open', 'verified');

insert into public.alerts (id, company_id, severity, type, title, message, status) values
('${ALERT_A}', '${COMPANY_A}', 'info', 'tenant_test', 'Alert A', 'Alleen voor A', 'open'),
('${ALERT_B}', '${COMPANY_B}', 'info', 'tenant_test', 'Alert B', 'Alleen voor B', 'open');
SQL

cat > "$WORKDIR/a.pdf" <<'PDF'
%PDF-1.4
% Synthetic tenant A document
%%EOF
PDF
cat > "$WORKDIR/b.pdf" <<'PDF'
%PDF-1.4
% Synthetic tenant B document
%%EOF
PDF

# Local-only credentials generated by Supabase CLI. These are never production secrets.
eval "$(supabase status -o env | grep -E '^(API_URL|ANON_KEY|PUBLISHABLE_KEY|SERVICE_ROLE_KEY)=')"
: "${API_URL:?local API URL missing}"
: "${SERVICE_ROLE_KEY:?local service-role key missing}"
PUBLIC_KEY="${PUBLISHABLE_KEY:-${ANON_KEY:-}}"
: "${PUBLIC_KEY:?local public API key missing}"

# Seed the two private original files through the real Storage API as service role.
for tenant in A B; do
  if [[ "$tenant" == "A" ]]; then path="$PATH_A"; file="$WORKDIR/a.pdf"; else path="$PATH_B"; file="$WORKDIR/b.pdf"; fi
  curl --fail --silent --show-error \
    -X POST "${API_URL}/storage/v1/object/company-documents/${path}" \
    -H "apikey: ${SERVICE_ROLE_KEY}" \
    -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
    -H "Content-Type: application/pdf" \
    --data-binary @"${file}" >/dev/null
done

echo "Signing in both synthetic users through the real local Auth API..."
TOKEN_A="$(curl --fail --silent --show-error \
  -X POST "${API_URL}/auth/v1/token?grant_type=password" \
  -H "apikey: ${PUBLIC_KEY}" -H 'Content-Type: application/json' \
  -d "{\"email\":\"tenant-a@example.com\",\"password\":\"${PASSWORD}\"}" | jq -r '.access_token')"
TOKEN_B="$(curl --fail --silent --show-error \
  -X POST "${API_URL}/auth/v1/token?grant_type=password" \
  -H "apikey: ${PUBLIC_KEY}" -H 'Content-Type: application/json' \
  -d "{\"email\":\"tenant-b@example.com\",\"password\":\"${PASSWORD}\"}" | jq -r '.access_token')"
: "${TOKEN_A:?tenant A access token missing}"
: "${TOKEN_B:?tenant B access token missing}"

rest_get() {
  local token="$1"
  local resource="$2"
  curl --fail --silent --show-error "${API_URL}/rest/v1/${resource}" \
    -H "apikey: ${PUBLIC_KEY}" \
    -H "Authorization: Bearer ${token}"
}

echo "Proving each user can read their own company data..."
test "$(rest_get "$TOKEN_A" "companies?id=eq.${COMPANY_A}&select=id" | json_len)" = "1"
test "$(rest_get "$TOKEN_B" "companies?id=eq.${COMPANY_B}&select=id" | json_len)" = "1"
test "$(rest_get "$TOKEN_A" "documents?id=eq.${DOCUMENT_A}&select=id" | json_len)" = "1"
test "$(rest_get "$TOKEN_B" "documents?id=eq.${DOCUMENT_B}&select=id" | json_len)" = "1"

echo "Proving cross-company reads return no rows..."
for resource in \
  "companies?id=eq.${COMPANY_B}&select=id" \
  "company_members?company_id=eq.${COMPANY_B}&select=company_id" \
  "documents?id=eq.${DOCUMENT_B}&select=id" \
  "invoices?id=eq.${INVOICE_B}&select=id" \
  "deadlines?id=eq.${DEADLINE_B}&select=id" \
  "alerts?id=eq.${ALERT_B}&select=id"; do
  test "$(rest_get "$TOKEN_A" "$resource" | json_len)" = "0"
done

for resource in \
  "companies?id=eq.${COMPANY_A}&select=id" \
  "company_members?company_id=eq.${COMPANY_A}&select=company_id" \
  "documents?id=eq.${DOCUMENT_A}&select=id" \
  "invoices?id=eq.${INVOICE_A}&select=id" \
  "deadlines?id=eq.${DEADLINE_A}&select=id" \
  "alerts?id=eq.${ALERT_A}&select=id"; do
  test "$(rest_get "$TOKEN_B" "$resource" | json_len)" = "0"
done

echo "Proving user A cannot modify company B..."
PATCH_RESULT="$(curl --fail --silent --show-error \
  -X PATCH "${API_URL}/rest/v1/companies?id=eq.${COMPANY_B}" \
  -H "apikey: ${PUBLIC_KEY}" \
  -H "Authorization: Bearer ${TOKEN_A}" \
  -H 'Content-Type: application/json' \
  -H 'Prefer: return=representation' \
  -d '{"name":"HACKED BY A"}')"
test "$(printf '%s' "$PATCH_RESULT" | json_len)" = "0"
test "$(run_psql -Atc "select name from public.companies where id='${COMPANY_B}'" | tr -d '\r\n')" = "Tenant B BV"

echo "Proving user A cannot create a document inside company B..."
CREATE_CODE="$(curl --silent --output "$WORKDIR/create-denied.json" --write-out '%{http_code}' \
  -X POST "${API_URL}/rest/v1/documents" \
  -H "apikey: ${PUBLIC_KEY}" \
  -H "Authorization: Bearer ${TOKEN_A}" \
  -H 'Content-Type: application/json' \
  -d "{\"company_id\":\"${COMPANY_B}\",\"uploaded_by\":\"${USER_A}\",\"original_filename\":\"forbidden.pdf\",\"mime_type\":\"application/pdf\",\"storage_path\":\"company/${COMPANY_B}/documents/99999999-9999-4999-8999-999999999999/original.pdf\"}")"
assert_http_not_2xx "$CREATE_CODE" "cross-company document insert"

echo "Proving private Storage allows own file but denies the other company..."
curl --fail --silent --show-error \
  "${API_URL}/storage/v1/object/authenticated/company-documents/${PATH_A}" \
  -H "apikey: ${PUBLIC_KEY}" \
  -H "Authorization: Bearer ${TOKEN_A}" \
  -o "$WORKDIR/own-a.pdf"

test "$(sha256sum "$WORKDIR/own-a.pdf" | awk '{print $1}')" = "$(sha256sum "$WORKDIR/a.pdf" | awk '{print $1}')"

CROSS_READ_CODE="$(curl --silent --output "$WORKDIR/cross-read.json" --write-out '%{http_code}' \
  "${API_URL}/storage/v1/object/authenticated/company-documents/${PATH_B}" \
  -H "apikey: ${PUBLIC_KEY}" \
  -H "Authorization: Bearer ${TOKEN_A}")"
assert_http_not_2xx "$CROSS_READ_CODE" "cross-company storage read"

CROSS_UPLOAD_CODE="$(curl --silent --output "$WORKDIR/cross-upload.json" --write-out '%{http_code}' \
  -X POST "${API_URL}/storage/v1/object/company-documents/${PATH_B}.forbidden" \
  -H "apikey: ${PUBLIC_KEY}" \
  -H "Authorization: Bearer ${TOKEN_A}" \
  -H 'Content-Type: application/pdf' \
  --data-binary @"$WORKDIR/a.pdf")"
assert_http_not_2xx "$CROSS_UPLOAD_CODE" "cross-company storage upload"

BAD_PATH_CODE="$(curl --silent --output "$WORKDIR/bad-path.json" --write-out '%{http_code}' \
  -X POST "${API_URL}/storage/v1/object/company-documents/not-company/${COMPANY_A}/documents/${DOCUMENT_A}/bad.pdf" \
  -H "apikey: ${PUBLIC_KEY}" \
  -H "Authorization: Bearer ${TOKEN_A}" \
  -H 'Content-Type: application/pdf' \
  --data-binary @"$WORKDIR/a.pdf")"
assert_http_not_2xx "$BAD_PATH_CODE" "non-canonical storage path"

echo "TENANT_ISOLATION_PASS own_reads=ok cross_reads=blocked cross_writes=blocked storage=blocked"
